version: '3.7'

services:
  frontend_akl:
    container_name: frontend_akl
    build:
    
    environment:

  frontend_all:
    container_name: frontend_all

    environment:


  backend:
    ports:
      - 3000:3000
    
    environment:
      - NODE_ENV=production

  database:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    volumes:
      - ./mongo-volume:/data/db

  http_server:
    image: nginx:1.19.2-alpine
    ports:
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"