export const CS_RANKS = [
  'Silver I',
  'Silver II',
  'Silver III',
  'Silver IV',
  'Silver Elite',
  'Silver Elite Master',
  'Gold Nova I',
  'Gold Nova II',
  'Gold Nova III',
  'Gold Nova Master',
  'Master Guardian I',
  'Master Guardian II',
  'Master Guardian Elite',
  'Distinguished Master Guardian',
  'Legendary Eagle',
  'Legendary Eagle Master',
  'Supreme Master First Class',
  'The Global Elite'
];

export const LOL_RANKS = [
  'IRON IV',
  'IRON III',
  'IRON II',
  'IRON I',
  'BRONZE IV',
  'BRONZE III',
  'BRONZE II',
  'BRONZE I',
  'SILVER IV',
  'SILVER III',
  'SILVER II',
  'SILVER I',
  'GOLD IV',
  'GOLD III',
  'GOLD II',
  'GOLD I',
  'PLATINUM IV',
  'PLATINUM III',
  'PLATINUM II',
  'PLATINUM I',
  'DIAMOND IV',
  'DIAMOND III',
  'DIAMOND II',
  'DIAMOND I',
  'MASTER',
  'GRANDMASTER',
  'CHALLENGER'
];
